version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:80
        volumes:
            - ./src:/var/www/html

    db:
        image: mariadb
        restart: always
        command: --init-file /var/init.sql
        volumes:
            - ./database:/var/lib/mysql
            - ./init.sql:/var/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cmsphp

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1